### PR TITLE
401 add some more last dates and content version types

### LINKED ISSUE #401: Add some more "last dates" and content version types
In Trainer we want to split out Reference Letter  document type
to "Client Reference" and "Professional Reference"
and add LastClientReference date  and LastProfessionalReference date
when you delete LastReference date, set it to LastProfessionalReference date

In Client we want to add these document types
"Application Video"  and LastClientApplicationVideo date
"CGC Form" and LastClientCGCForm date

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes

1. Added content version types and fields to contact.
2. Updated trigger.
3. Updated tests.

# Issues Closed
#401

### CODE REVIEW

**Comment by atlasjen** [comment]
I'm getting this error in a new scratch org
                    Skipping task update_package_xml (skipped unless project_config.project__source_format != "sfdx" or not org_config.scratch)      
                    Skipping task deploy (skipped unless project_config.project__source_format != "sfdx" or not org_config.scratch)
                    ------------------------------------------------------------
                    Running task: dx_push
                    ------------------------------------------------------------

                    Options:
                      command: force:source:push
                    Beginning task: SFDXOrgTask

                    Running command: sfdx force:source:push -u test-eawhej2vd2ef@example.com
[02/03/23 16:44:20] Pushing v55.0 metadata to test-eawhej2vd2ef@example.com using the v56.0 SOAP API
[02/03/23 16:45:50] Pushing v55.0 metadata to test-eawhej2vd2ef@example.com using the v56.0 SOAP API
                    Pushing v55.0 metadata to test-eawhej2vd2ef@example.com using the v56.0 SOAP API
[02/03/23 16:45:56] Check the order of your dependencies and ensure all metadata is included.

                    === Component Failures [1]

                     Type  Name  Problem
                     ───── ───── ───────────────────────────────────────────────────────────────
                     Error Admin In field: field - no CustomField named Contact.CGCForm__c found

[02/03/23 16:45:57] Return code: 68
                    stderr: ERROR running force:source:push:  Push failed.

                    Exception in task deploy_unmanaged.dx_push

Error: Return code: 68
stderr: ERROR running force:source:push:  Push failed.

**Comment by deb761** [comment]
I missed that error. Will push the fix presently. Sent from my iPhoneOn Feb 3, 2023, at 4:51 PM, atlasjen ***@***.***> wrote:﻿
I'm getting this error in a new scratch org
Skipping task update_package_xml (skipped unless project_config.project__source_format != "sfdx" or not org_config.scratch)
Skipping task deploy (skipped unless project_config.project__source_format != "sfdx" or not org_config.scratch)
------------------------------------------------------------
Running task: dx_push
------------------------------------------------------------
                Options:
                  command: force:source:push
                Beginning task: SFDXOrgTask

                Running command: sfdx force:source:push -u ***@***.***

[02/03/23 16:44:20] Pushing v55.0 metadata to ***@***.*** using the v56.0 SOAP API
[02/03/23 16:45:50] Pushing v55.0 metadata to ***@***.*** using the v56.0 SOAP API
Pushing v55.0 metadata to ***@***.*** using the v56.0 SOAP API
[02/03/23 16:45:56] Check the order of your dependencies and ensure all metadata is included.
                === Component Failures [1]

                 Type  Name  Problem
                 ───── ───── ───────────────────────────────────────────────────────────────
                 Error Admin In field: field - no CustomField named Contact.CGCForm__c found

[02/03/23 16:45:57] Return code: 68
stderr: ERROR running force:source:push:  Push failed.
                Exception in task deploy_unmanaged.dx_push

Error: Return code: 68
stderr: ERROR running force:source:push:  Push failed.

**Comment by atlasjen** [comment]
failed w new repo and new scratch org push 
[02/06/23 22:21:22] Beginning task: SFDXOrgTask

                    Running command: sfdx force:source:push -u test-k2qzkvwacdlv@example.com        
[02/06/23 22:21:27] Pushing v55.0 metadata to test-k2qzkvwacdlv@example.com using the v56.0 SOAP API[02/06/23 22:22:49] Pushing v55.0 metadata to test-k2qzkvwacdlv@example.com using the v56.0 SOAP API[02/06/23 22:22:53] Check the order of your dependencies and ensure all metadata is included.       
                    
                    === Component Failures [1]

                     Type  Name  Problem
                     ───── ─────
                    ─────────────────────────────────────────────────────────────────────────────── 
[02/06/23 22:22:54]  Error Admin In field: field - no CustomField named
                    Team__c.CertificationValidUntil__c found

[02/06/23 22:22:55] Return code: 68
                    stderr: ERROR running force:source:push:  Push failed.

                    Exception in task deploy_unmanaged.dx_push

**Comment by deb761** [comment]
Doh!  fixed.

**Pull request merged**
