### PR TITLE
Create component to show related Client logs in Team page

### LINKED ISSUE #404: Can we access logs under teams?
It occurs to me that logs really are associated w a team not just a client...

can we reuse the same LWCs you have under contact and also show the client and TF logs as related items under teams and add them there as well? I'm not sure if you need different logic or not, since you should still have access to the client ID.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes
Created component to show client logs in the Team related object section.  Same idea as I did with the files.

# Issues Closed
#404

### CODE REVIEW

**Comment by deb761** [comment]
Show both Client and Team Facilitator logs.

**Comment by atlasjen** [comment]
I can see client logs. However, when i enter a TF log for that client, the TF logs do not appear.
I tried this w/ the sample data for Zoe Harding

What i have on the client:
image

What i see in teams:
image

**Review by atlasjen — CHANGES_REQUESTED** [review]
see comment. i am not seeing the TF logs for the client in teams

**Comment by deb761** [comment]
My bad.  I forgot to add the other component.  Coming up.

**Comment by atlasjen** [comment]
@deb761 I'm not seeing a new commit on this branch.

**Comment by deb761** [comment]
Just added the TeamFacilitator logs

**Comment by atlasjen** [comment]
look good.

**Pull request merged**
