### PR TITLE
Feature/cleanup modals

### PR DESCRIPTION
**Pull request by deb761**
Made this change to simplify the code for these forms.

# Critical Changes

# Changes
Removed use of message channel for CEU, File, and Background Check forms

# Issues Closed

### CODE REVIEW

**Comment by atlasjen** [comment]
what should i be looking for to test this?

**Comment by deb761** [comment]
Just a quick regression test to make sure I didn’t break anything.

**Comment by atlasjen** [comment]
I looked through the files you worked on and tried to test those areas.

**Background check:**
I test out making a new background check record (via the menu quick access, not a contact)
I initially tried to make it w/o an attachment, then added an attachment and got this error
image

I tried the same thing via a contact, and it completed just fine.

_**Note, while you are in this, can you make the file attachment optional for background checks? If it is pending, we won't have a file yet.**_

**CEU**
I tried creating a CEU and didn't have any issues.

**Puppy Logs**
All seems fine

**Related Files on Contacts**
All seems fine

**Comment by deb761** [comment]
Fixed.  Hopefully you won't need a fresh scratch org to test.  This one doesn't have the updates to the logs, so don't use a scratch org with those.

**Comment by atlasjen** [comment]
I pulled this to a new scratch org. getting this error. Not sure if this is in the current commit or no.
image

I was able to get past the previous issue and add a BG check w/o issue.

I saw you had made edits to to CEU so tested that too. all good from this aspect.
If this checkin does not remove requiring a file for background checks, please just fix the merge error and commit.

**Comment by deb761** [comment]
Merged successfully.  Closing.

**Pull request merged**
