### PR TITLE
382 custom report needed to have dog information for tsim folks

### LINKED ISSUE #382: Custom report needed to have dog information for TSiM folks
While salesforce does support joined reports, they do not support inner joins.. thus your "joined" report is really just two independent reports. lame! lots of open issues on this.

So, thus, i have no way to get the report i want which is very close to this one if only i could do an inner join to see the proper dog on the same line as the person and i want to be able to see and see a few more dog fields.
https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UYoVEAW/view?queryScope=userFolders

here would be the query (ish) select programassignment.contact where ProgramAssignment.Program = "Teams Set in Motion" and programassignment.Status contains ("In progress", "Observer", Pending") and then join that client with client.dog to include the dog name, age, breed, gender

Here are the columns i want to see from programassignment and contact and https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UYfxEAG/view?queryScope=userFolders

From dog i then want: Dog Name, age, breed, gender

This is the one report so far i haven't been able to figure out how to do.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes
Created report and LWC to show it in.
LWC has a download button to download result to a csv file.

# Issues Closed
#382

### CODE REVIEW

**Comment by deb761** [comment]
The LWC currently isn't attached to any pages.  You can add it to a home page.  Ping me if you need help.

Also, the sample data on this branch doesn't have any TSiM assignments.

**Comment by atlasjen** [comment]
small modifications
- make address not required
- show even if a dog is not set
- rename header "address" to "Location"
- remove link header
image

**Comment by atlasjen** [comment]
Sent you a slack comment, but I can't presently deploy this to a scratch org.

**Comment by atlasjen** [comment]
Looks good. Can you resolve the conflicts and commit/merge?

**Pull request merged**
