### PR TITLE
Bug/229 contact items

### LINKED ISSUE #229: Contact Issues
Creating a new issues for items still open when committing bug/220-contact-changes

FIXED! 1) Atlas Contact Layout not set for Administrator by default but even when it tried manually setting it, i can't see it, so there may be some other setting that needs to be changed

2) New Contact form needs some fixing for pronoun, then a few tweaks

-if they choose "Specify" for Pronoun, they need a way to enter their value. 
Fine to just add the Specify pronoun text field as another field.

In the upper contact section, also add

- Preferred Language and Alternate Language
- Birthdate

In the additional information section add
- Description

3) Contact List updates
"All" isn't showing up, 
image

Can you fix the typo on "Donor". Let's keep it. I realized it is a position.
image

Add "Trainer" as filter type

### PR DESCRIPTION
**Pull request by deb761**
# Changes

Add listviews to Contact
Fix problem with specified pronouns in new contact & use field imports
Make pronoun a single picklist
Add email and phone to sample data mapping (but didn't re-run sample data)

# Issues Closed

#229

### CODE REVIEW

**Review by atlasjen — CHANGES_REQUESTED** [review]
I tried to use the "new" form for contact.
I manually set a value in the specify pronoun text field.

I picked one of the standard pronouns, They/them  and then tried again with he/him.
I got this error:
[NoErrorObjectAvailable] Script error.
a()@https://static.lightning.force.com/cs92/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:1025:196
{anonymous}()@https://static.lightning.force.com/cs92/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:1025:389
dispatchEvent()@https://static.lightning.force.com/cs92/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:21:32794
R.dispatchEvent()@https://static.lightning.force.com/cs92/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:21:8008
R.handlePicklistProgrammaticChange()@https://power-efficiency-8857-dev-ed.lightning.force.com/components/lightning/inputField.js:1:19011
R.handleChange()@https://power-efficiency-8857-dev-ed.lightning.force.com/components/lightning/inputField.js:1:18251

**Comment by atlasjen** [comment]
i also noticed that by default whatever is set for preferred language is also set for Alternative language.. OR it is that english is the default for both. Can we have nothing as the default for alternative?

image

**Comment by atlasjen** [comment]
Note, listviews in Contact look great :)

**Comment by deb761** [comment]
Stupid mistake with the pronouns.  Fixed with the next push.  The default is tied to the picklist, so we're stuck with the same default for both.  No default, then?

**Comment by atlasjen** [comment]
Yep no default

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atlasjen** [comment]
Yep, New form is working now. Please just remove the default on language and we are good to commit this one.

**Comment by deb761** [comment]
Done.

**Pull request merged**
