### PR TITLE
Show local date in related files

### LINKED ISSUE #296: File upload saves on previous date
I noticed as I was uploading files for Dog (Charlotte) that the dates would be assigned to the previous day vs the day I entered.
I need to do a bit more testing to see if it is always the previous day or only on a weekend.

Accuracy is good enough for our purposes, but recording to examine later.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes

Changed date in related files to date-local to match entered date.
Removed update to last* files because that is in the trigger now.

# Issues Closed
#296

### CODE REVIEW

**Review by atlasjen — CHANGES_REQUESTED** [review]
The dates look good, however, i am seeing the Last* date not set in some cases.
I test Client/LOMI and the Last* date is not displaying.
Client/TSIM application late date is mapped just fine.

**Comment by deb761** [comment]
I’ll check that. Maybe the trigger is missing that one.

**Comment by atlasjen** [comment]
thanks! do the unit tests have each date included?
________________________________

**Comment by deb761** [comment]
They are supposed to. I may have missed one.

**Comment by deb761** [comment]
They do have Client/LOMI.  Not sure why it wasn't showing in the browser.

**Comment by atlasjen** [comment]
ok i just tested it again and the date came through. merging.

**Pull request merged**
