### PR TITLE
395 405 team status

### LINKED ISSUE #395: Teams/Client/Dog Status
In working on a report of how many teams we've ever certified, i realized i can't pull that form a contact's client status as that is their current status.. i need to be able to look at the team... but there is no status.

Here is my suggestion

- we set status on team manually
- there is a trigger to set it on client and dog to be the same thing. If there was already a status on the dog or client, we overwrite it w/ what is in team
- if someone happens to manualy edit the client/dog status later, oh well.  The next time it is updated in the team, we stomp on it.

this is actually staying consistent w/ how we derive certification valid until on the client from the team.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes

1. Moved LastClient*Dates to Team.
2. Added Team status.
3. Added linking these files also to the Client and dog.
4. Removed LastClient* Dates from Contact layout and added them to Team layout.
5. Added linking dog files to all teams they are in.
6. Added copying Team status to ClientStatus on the client contact along with CertificationValidUntil.

# Issues Closed
#395 #400 #405

### CODE REVIEW

**Comment by deb761** [comment]
Note: I'm not done yet, just wanted to continue the conversation.  I don't have any tests in that check the CDL is created for the contact or dog.  I thought I did, but I don't see them anywhere.

**Comment by deb761** [comment]
This is ready for review now.  Sorry about the delay.  I'm in water heater/repipe limbo.

**Comment by atlasjen** [comment]
Good deal. I am out of town at a conference until Friday. I will see if I have breaks and can review before then
Good luck on the piumbing!

**Comment by atlasjen** [comment]
1. I thought we made this 2 way so that if files were added on client or dog, they would also show on team and vice versa. Maybe I am incorrect. Maybe it was just dog that was to be 2 way.
*I tested the use case of if client files were added to the client before the team existed. I would have expected them to also show in the team, as well as the "last date" once the team was created.
*I also tested adding "client" files to the client once the team existed and they didn't show in the team, nor did the "last date"
*I also tested adding "dog" files to the client once the team existed and they didn't show in the team, nor did the "last date"
I do know we were not going to have status be 2 way and that was just from the team and would overwrite anything in client/dog..
I am almost positive we talked about this one being 2 way for the dog since loading the dog files will also be the time they set the vet health info, so they'd be in the dog object.

The trick w/ this is we'd have to always make sure it was the right client/dog being updated. this isn't a problem from team->client/dog but from dog/client->team could be. we'd have to be careful it is going to the proper team, not just any team that client was in. thinking about that, not sure how we'd do that from client since they will still have the relationship to the old dog and old team.  From the dog, my recollection is we said dog records are dog records and would apply to any team, thus ok to overwrite.

3. Dog status doesn't update when team status does.
I updated the status in team. It correctly updated in the client but not the dog.

4. were we going to display the dog health status block in the related list in the team somewhere? The one rollup field "health record status" would be fine.

5. It looks like "certification valid until" doens't populate on the team when the PAT value is set. Realizing in our model certification valid until is the exact same as PAT valid until.. so since we are no longer showing it on the client, that is redundant. We can drop "certification valid until"

6. We should display Client and Team Facilitator Logs related LWCs in the Team as well.

some other tests that worked as expected
* Files added to team show up in client or dog w correct dates as expected
* contact status updates when team status is updated
* loading PATs  sets PAT Valid Until in the team.

**Comment by deb761** [comment]
1. I only made it one-way, since contact-team and dog-team is a 1 to many, we can't be sure which team to attach a document to.
2. Yep.  Looks like I missed updating the dog status.
3. I was going to add dog health in another PR.
4. The logs are in a different PR.
5. In Issue #395, you asked for the trigger after manually setting team status.  It is _very_ frustrating when you change the acceptance criteria.

**Comment by atlasjen** [comment]
1. Agreed 1 way makes sense on the client but we had talked about for the dog anything on the dog would apply to any team since it is health info. . since they have to manually set the vaccination info at the same time as uploading the files, having to do that in 2 locations is going to be really inefficient. open to other ideas if we want to move some of the dog stuff into team.

sorry on 3,4,6. 

5. I'm confused the issue you referenced just refers to status which is indeed setting manually on the team then sets it on dog and client. Nothing changed there.  I was bringing up realizing we didn't need to move Certification Valid Until to the team as it is redundant w/ the PAT valid value which does already get set.

**Comment by deb761** [comment]
So in 1 you are saying the dog status should overwrite the team status _AND_ the team status overwrites the dog status?

**Comment by atlasjen** [comment]
This is likely an easier one to get on a call to go over. Let me know if you have any time this weekend. I am doing a lot of various sessions w clients but can def make time

**Pull request merged**
