### PR TITLE
Change TSiM to Standalone

### LINKED ISSUE #305: Changes to standardize standalone programs vs TSiM
Going with what you suggested in the first place and using reports from Program Assignments to figure this stuff out. Note, this can wait until 1.2 assuming we get that out in the next few months.
We can do some data munging then. it doesn't impact that many records.

Let's
- drop TSiM dates from Contact (last TSiM Application, last TSiM program Agreement)
- drop "In TSiM" status from Contact.ClientStatus picklist
- in the file upload LWC
  - Change Category "Teams Set in Motion" to "Standalone Programs"/ disable TSiM and add "Standalone Programs" if needed
  - they still get the same two file types of application and agreement and contact form. if they use application or agreement, no Last* dates to track. Same logic applies for contact form as for anyone else, we still track that date.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes
Change TSiM to Standalone Programs in File type list
Remove Last TSiM file dates from Contact layout

# Issues Closed
#305

### CODE REVIEW

**Comment by atlasjen** [comment]
Question:
What happens for files previously uploaded as TSiM. Do they change to Standalone programs? Or do we need to change that?
Otherwise, it works as expected and we can merge, but curious about that.

**Comment by deb761** [comment]
Not 100% sure, but I think they would remain as TSiM. I could write an install script to update.

**Comment by atlasjen** [comment]
if we can do the data munge that would be good vs going and manually updating the files.
________________________________

**Comment by atlasjen** [comment]
merging. we just need to munge the data once live.

**Pull request merged**
