### PR TITLE
Update status fields

### LINKED ISSUE #108: Update Status to match all in "positions statuses and files" tab
cleanup all status picklists. see excel file for details.

### PR DESCRIPTION
**Pull request by deb761**
Fixes #108

I didn't touch the ContentVersion object, since I saw the picklist values were already added.  *BUT*, there are now two fields for the position and type.  Presumably @kaurarjinder is using the new fields for the file component.  I just need to make sure which field is which before removing any redundant fields.

### CODE REVIEW

**Comment by atlasjen** [comment]
this also has some merge errors.. again, do I need to deploy from scratch again?

**Comment by kaurarjinder** [comment]
following fields are referenced in my code :
Title, ContentDocumentId, Type__c, Positions__c, Position_Files__c,
Document_Type__c

**Comment by deb761** [comment]
Yes.

**Comment by atlasjen** [comment]
okey dokey. will start that again tonight for each of the remaining two
________________________________

**Comment by atlasjen** [comment]
so I am fine w/ your merging. but this isn't an issue w/ me creating a scratch org, it is an issue w/ fixing the files to allow a merge and Im not sure how to do that. changes look fine. Please resolve the conflicts, do the merge and commit.

**Comment by deb761** [comment]
Will do.

**Pull request merged**
