### PR TITLE
Bug/pat fields

### LINKED ISSUE #180: PAT updates
**The PAT schema looks good other than 2 things:**
1) I think we want a "pat number" field that ideally automatically increments so we know is it 1, 2, 3  etc. This is going to be needed for
2) we want a PAT due derived field.  If the previous PAT was 1 or 2, then it is due at the end of the same quarter the following year. So if in Jan 2021, then due by end of March 2022.  If the previous PAT was 3 or later, it is due EVERY other year, same logic as quarter
3) I realized Role goes away.  We just need to require dog, client, assessor on each.

**The PAT new form should have more required fields:**
* status, location, client, dog, assessor
* "Assessor" then becomes a required field

**The PAT related pane for contacts should have an easier way to see the attached PATs.** 
right now you have to choose edit and can scroll to the files. can it have a link to the pdfs and let them be brought up?

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes
Created Team object defining Client, Dog, Handler, Facilitator

# Changes
Created layout and Tab for Teams.  Moved related PATs to Teams layout

# Issues Closed
#180

### CODE REVIEW

**Comment by atlasjen** [comment]
What will the flow be to create a team? I assume we'd first need a dog, client, facilitator as objects and then they are associated in the team vs in the contact? Trying to think through this for both complexity in form assembly or for the human entering data as well as reporting.
I think we may be getting too hierarchical for human/GUI usability.
I was onboard w moving the concept of PAT due date to a team but i am worried about some of these other changes.

-----
Separate note [ added after comments below] .. that i added at end, i see that my PUSH didn't get everything that i am expecting based on reviewing the changes in github. I am going to do a fresh deploy
-----
**TEAM object**
* Primary and Secondary Certification have incorrect picklist values. It looks like we've had them incorrect all along. They correct list for each is the same and it should be
Allergen Alert	
Autism
Diabetes Alert	
Hearing Alert	
Medical Alert	
Medical Assistance
Mobility	
Psychiatric	
Seizure Response 

* A team can have more than one TF... They will at a minimum always have a TF and a TF Lead. I am fine w/ those just being classified in the Team as TF(s) but we should be able to have more than one.

* I don't see client anywhere. 

* Handler needs to be a part of the team. it is optional but it is a key component. If it is necessary to have a handler due to the client not being able to manage the dog on their own, then the team only has public access rights under the ADA if the handler, client and dog are all together.

*Let's rename the Next PAT due to PAT Valid Until just like we have on PAT to be consistent.

*what about the dog??  or dog(s)

**PAT object**
I am a bit worried about this referencing Team and dropping client, handler dog. I know why you did it and it is redundant, but how much harder does it make for the end user to get their answer to simple questions like when is a pat due and for whom?
I am assuming we can query from form assembly to get the right Team ID 

---
I did a PUSH vs a fresh deploy to a scratch org and i am not seeing all of the changes in my org that i see in the commits in github. I am going to pause here and do a fresh deploy and see if that changes things..

**Review by atlasjen — CHANGES_REQUESTED** [review]
See my comment below.. i think it might be good to have a call to talk about data model impacts on how the user will add and find data in the UI as well as how we will import/load data in.  I am going to continue testing.

**Comment by deb761** [comment]
@atlasjen This is ready to review again.

**Comment by atlasjen** [comment]
testing now.. just tried adding a PAT record to team and after trying to upload a file, got this error. 
image
Here is the "technical stuff"
`[NoErrorObjectAvailable] Script error.
a()@https://static.lightning.force.com/cs96/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:1025:196
{anonymous}()@https://static.lightning.force.com/cs96/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:1025:389
dispatchEvent()@https://static.lightning.force.com/cs96/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:21:32794
r.dispatchEvent()@https://static.lightning.force.com/cs96/auraFW/javascript/2yRFfs4WfGnFrNGn9C_dGg/aura_prod.js:21:8008
onUpload()@https://agility-force-4917-dev-ed.lightning.force.com/components/lightning/fileUpload.js:1:1977
Object.onFinalUploadComplete()@https://agility-force-4917-dev-ed.lightning.force.com/auraCmpDef?aura.app=markup://one:one&aura.mode=PROD&_au=H0m4rvdFHzPK3893_VSkIQ&_ff=DESKTOP&_l=true&_lrmc=1730203071&_l10n=en_US&_c=false&_style=-1720540562&_density=VIEW_ONE&_def=markup://forceContent:fileUploadAction&_uid=LATEST-4:5:213
onFinalUploadComplete()@https://agility-force-4917-dev-ed.lightning.force.com/auraCmpDef?aura.app=markup://one:one&aura.mode=PROD&_au=H0m4rvdFHzPK3893_VSkIQ&_ff=DESKTOP&_l=true&_lrmc=1730203071&_l10n=en_US&_c=false&_style=-1720540562&_density=VIEW_ONE&_def=markup://forceContent:fileUploadAction&_uid=LATEST-4:1:442`

**Comment by atlasjen** [comment]
A new update, i am able to save a file in Edit, not in New.

**Comment by atlasjen** [comment]
I tried saving "None" as a status and it won't let me due to being required. I think that means we need 'Pending Review' or 'Pending' as a status

**Comment by deb761** [comment]
Thanks for the write up.  Guess I was getting bleary-eyed on this one.

**Comment by deb761** [comment]
Give it another try.  Should be cleaned up.

**Comment by atlasjen** [comment]
Much better!
I just added a commit to swap "related" vs "details" on the team page.

Couple of minor things

1. can you add "pending review" as a PAT status
2. Can you have the related Team entry under Contact be combined, much like you did for logs. Here is what i see here:
image

After those, ready to merge!!!

**Comment by deb761** [comment]
Can we push merging the two relations to 1.1?  It involves creating at least 2 LWC.

**Comment by atlasjen** [comment]
yes if needed. I wasn't sure how much effort was involved.  i expect we will end up w a list of fixes for a quick re-release for 1.1 and can roll this to that
________________________________

**Pull request merged**
