### PR TITLE
Create permission sets

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes
Added several permission sets, including Atlas Base

# Issues Closed

### CODE REVIEW

**Comment by atlasjen** [comment]
I first tried just updating my existing scratch org and got this error, so i started fresh.
image


I tried running this on a new scratch org and got this error. Note, i realized after the fact that i also got this API warning when i tried to do a push up above.
image

**Comment by deb761** [comment]
Try updating your cumulus ci.  pipx upgrade cumulusci

**Comment by atlasjen** [comment]
i updated it.. still the same issue. there are two things here, 

1 is the error adding the sample data.
2 is the cumulus error

**Review by atlasjen — CHANGES_REQUESTED** [review]
see comment below. i have the latest cumulus version. I am not seeing this error w other PRs (like the one where you added initial certification dates) just this one.

**Comment by atlasjen** [comment]
ran successfully this time

**Comment by atlasjen** [comment]
- Background check does what is expected.
- Demographic does what is expected.
- Tested the Team permission set.

It adds Client permissions, which is expected but it did not add dog permissions.
I get this error when i try to open the related dog.
image

I would expect Team to also include Client and Dog.

**Pull request merged**
