### PR TITLE
Remove default values for category and type in lwc

### LINKED ISSUE #477: Error when select Upload Files on Contact
testing in staging, I tried contact "fred test" and went to related files and chose upload.
image

I have a feeling it is due to "Board member" or "Staff/Contractor" being one of the positions. If either position is set, this error happens. If they are not, it works.

update: also failed if "Team Facilitator" is set as a position. Does work if "client" is set.

### PR DESCRIPTION
**Pull request by deb761**
Add CategoryRule data to beta dataset

# Critical Changes
Fixed null reference exception when uploading files using the component with no document category and type defined.

# Changes

# Issues Closed
#477

### CODE REVIEW

**Comment by atlasjen** [comment]
I tried going from Theodore Hale's contact record and chose to upload w/o category or type specified and get this error
image

**Comment by atlasjen** [comment]
Good news is i no longer get an error when i pick Staff/Contractor as type and am able to upload those, so must be related in some way to the same fix.

**Comment by deb761** [comment]
I deployed a fresh scratch org, and added a file with no category or type to Theodore Hale without getting that error.  I'm not sure how you got it.

**Comment by atlasjen** [comment]
i had the wrong branch checked out. works for me.

**Pull request merged**
