### PR TITLE
Bug/220 contact changes

### LINKED ISSUE #220: Contact object updates
Discovered these while debugging inserts/exports
**Let's add some fields:**

1.  Preferred Language (single select)
2.  Alternate Languages (free text field)

Here is a picklist for Preferred Language picklist- these are in the lists of most common, in order of most common in US (at least the top ones are). But maybe we just do English and then the rest alphabetical?

- English
- Spanish
- Chinese
- Tagalog
- Vietnamese
- Arabic
- French
- Korean
- Russian
- German
- Italian
- Portuguese

3.  Middle Name and Suffix. These already exist, we just need to enable them

image

---

**Last Received Date Field changes:**
Change "Puppy .." to  "Puppy Raiser ..."
image

For Contact Form, we don't need to have different last received for the different roles. Let's just save 1 date for contact form.
So remove:
image

and just make it Last ContactForm  ContactFormReceived__c

Any of these would update the same record and same date.
So "Contact Form" could be an option if "None" is selected as the category OR we could add it to all Categories. Whichever is easiest.

I noticed it is not currently available under TSiM, ADSiM or Staff 

It can then go  to the page layout here:
image

---

**Pronoun Picklist**
can you capitalize these? I just think it looks better in the data
They/Them
He/Him
She/Her

also, right now the fact that the actual value is different than we get in our forms means we need to postprocess. I am doing that for dataloader, but not sure if that is viable for form assembly. For example, the actual picklist value for "They/Them" is "They". So i have to munge the data to have it load properly. Would it work to have  the picklist values match the full display value? I may hate myself for this as that means i am back dealing w/ "/" for import, but i think it is less extra processing.

---

**Position**
It appears Volunteer is set by default. We should have it blank/None by default

### PR DESCRIPTION
**Pull request by deb761**
# Changes

1. Added language fields
2. Merged Last ContactForm fields
3. Capitalized pronouns and made field value match label

# Issues Closed

Closes #220

### CODE REVIEW

**Comment by deb761** [comment]
The two settings will need to be unpackaged metadata.  I'll get it with the other metadata in another pull request.

**Review by atlasjen — CHANGES_REQUESTED** [review]
Can you do a couple of tweaks for me? I tried to do (1) but when i did a pull i got all kinds of other stuff so scrapping that

(1)
Change the toplevel contact layout to be this order:
image

Then:
(2) Last Contact Form does not display in the page layout. Are the permissions set properly?

image

(3) got an error trying to add a file w/ the label of Contact Form
I happened to Volunteer, then Contact form. Here is what i saw after it said upload successful.:
I saw the same thing trying Staff, etc, just w different errors.   Looks like this needs to be updated to set the new field.
image

(4) There doesn't appear to be a generic notes field. There is a generic Description field. can we change the display label on that to be "Notes/Description" or no? If no, perhaps rather than using Description we should add "Notes". I want to use this field to map in general comments such as might be on the contact form.

(5) New Contact form needs some fixing for pronoun, then a few tweaks
* if they choose "Specify" for Pronoun, they need a way to enter their value.  Can we have it show the "Pronoun (Entered)" if they choose specify?  
In the upper contact section, also add
* Preferred Language and Alternate Language
* Birthdate
In the additional information section add
* Notes

**Comment by deb761** [comment]
I'm working on the FileController for that, too.
Notes is a related list.
I set up Alternate Languages as a Multi-Select Picklist.  Does that work?

**Comment by atlasjen** [comment]
That works for Alternative Languages. I saw that. I will update our forms accordingly.
AH! i see on notes.
hmm. so i was thinking for key important items like what they put in their emergency contact form.
maybe we just add a field "Critical Comments" or something like that?
or we train people to look at notes. setting them is just a lot more of a pain in dataloader but we can dothat.

________________________________

**Comment by atlasjen** [comment]
Let's remove this filter.. Donor isn't a position and we can use the built in salesforce donor stuff once we get there.
image

**Comment by atlasjen** [comment]
Data didn't load properly. need to fix the sample data for pronoun
```
[05/15/22 09:54:41] --------------------------------------------------------                    ----
                    Running task: load_dataset
                    --------------------------------------------------------                    ----

                    Options:
                      mapping: datasets/mapping.yml
                      sql_path: datasets/sample.sql
                      ignore_row_errors: False
                      inject_namespaces: True
                      drop_missing_schema: False
                      set_recently_viewed: True
                    Beginning task: LoadData

[05/15/22 09:54:51] Using temporary database
                    C:\Users\jen\AppData\Local\Temp\tmpoe0bai8a\temp_db.db
                    Running step: Insert Program__c
                    Creating DataOperationType.INSERT Operation for
                    Program__c using DataApi.SMART
                    Prepared 176 rows for DataOperationType.INSERT to
                    Program__c.
[05/15/22 09:54:52] Running step: Insert npo02__Household__c
                    Creating DataOperationType.INSERT Operation for
                    npo02__Household__c using DataApi.SMART
                    Prepared 0 rows for DataOperationType.INSERT to
                    npo02__Household__c.
                    Running step: Insert npsp__Batch__c
                    Creating DataOperationType.INSERT Operation for
                    npsp__Batch__c using DataApi.SMART
                    Prepared 0 rows for DataOperationType.INSERT to
                    npsp__Batch__c.
                    Running step: Insert Lead
                    Creating DataOperationType.INSERT Operation for Lead
                    using DataApi.SMART
                    Prepared 7 rows for DataOperationType.INSERT to Lead.
**[05/15/22 09:55:07] Exception in task config_dev.load_dataset

Error: Error on record with id 1: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST:
Pronoun: bad value for restricted picklist field: he (Pronoun__c)
Run this command for more information about debugging errors: cci error
--help**
PS C:\Users\jen\Documents\GitHub\atlas-dogs> cci org browser dev
[05/15/22 09:59:41] Getting org info from Salesforce CLI for test-5tbzdiezat8v@example.com
PS C:\Users\jen\Documents\GitHub\atlas-dogs> 
```

**Comment by atlasjen** [comment]
All built and deployed perfectly! yay!

I wasn't seeing the page layout I expected for Contact. I assigned "Atlas Contact Layout" to the System Administrator. Those settings had been lost... but it still isn't displaying, I am not sure if that is a caching issue. I know layouts can sometimes take a while to display.

This is limiting me checking much.. 

Looking at other items on this issues:
1) I am seeing that "doner" is still present in the contact filter list.

2) The New Contact form still needs updating (per #220 )

I will check again tomorrow to see if cache has cleared. I did go to developer mode on chrome and do a hard dump and clear.

thank you!

**Comment by atlasjen** [comment]
@deb761 yep, accidentally merged. let me know what you want to do . Not deleting branch yet.

**Pull request merged**
