### PR TITLE
363 set name for ceu

### LINKED ISSUE #363: Set name for CEU
Salesforce won't let us change that object name to auto-number.  So we need to give these objects appropriate names.  Let's go with [Authority]-[Date], since the length of both of these is known, and title isn't.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes
Reverted change to CEU name type

# Changes
Added trigger to set CEU name to CEU-{0000}

# Issues Closed
#363

### CODE REVIEW

**Review by atlasjen — CHANGES_REQUESTED** [review]
works great from contact.
From the CEU object itself, it still wants a name set 
image

i would assume it would be much like program assignment that it just sets it in the backend.

**Comment by deb761** [comment]
We can't change the new object layout.  Best we can do is override the new button like we do with Dogs and Contacts.

**Comment by atlasjen** [comment]
Ok. What is it you did w program assignments? That sets the name automatically

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by deb761** [comment]
Program Assignment was set up as an auto-number name.  We can't change CEU to that since we released the CEU object type in 1.0.

**Comment by deb761** [comment]
I overloaded the new CEU button to show our new CEU form.  That should solve the initial name problem.

**Pull request merged**
