### PR TITLE
Bug/ceu form

### LINKED ISSUE #179: CEU "new" form fixes
The CEU datamodel looks perfect.
**CEU New Form**
1.The CEU "new"  form does not bring up a place to put a value for CEU Authority Other, if other is chosen.
2. More fields need to be required. Let's require program date, date completed, [date submitted should be automatic and not a field they fill out], program hours, requested ceus, program authority, trainer, role.

**CEU detail view**
We need a way to attach documentation w/ each CEU. This should be an option in the NEW form and then something that can be clicked on  should bring that attachment up for the user to see.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes
Made fields required in CEU object.  Created custom form to allow attaching files.

# Changes
Moved related CEUs into a custom LWC.

# Issues Closed
#179

# New CEU
image

# Edit CEU
image

I have not added a means to delete files yet.  I think we can do that with v1.1

### CODE REVIEW

**Comment by atlasjen** [comment]
tested via  push after reviewing previous 2 PR's vs a new scratch org. Here is the error I got:

PS C:\Users\jen\Documents\GitHub\atlas-dogs> cci task run dx_push  --org dev
[04/14/22 21:38:58] Getting org info from Salesforce CLI for test-bvrowggftqlp@example.com
[04/14/22 21:39:00] Beginning task: SFDXOrgTask
                    As user: test-bvrowggftqlp@example.com
                    In org: 00D7A0000000ix7

                    Running command: sfdx force:source:push -u test-bvrowggftqlp@example.com
[04/14/22 21:39:02] *** Pushing v50.0 metadata with SOAP API v53.0 connection ***
[04/14/22 21:39:27]
                    === Component Failures [1]
                    Type   Name   Problem
                    ─────  ─────  ──────────────────────────────────────────────────────────────────────────────────
                    Error  Admin  You cannot deploy to a required field: ContinuingEducationUnit__c.DateSubmitted__c

[04/14/22 21:39:28] Return code: 1
                    stderr: ERROR running force:source:push:  Push failed.


Error: Return code: 1
stderr: ERROR running force:source:push:  Push failed.

**Review by atlasjen — CHANGES_REQUESTED** [review]
Please see comment re error.

**Comment by atlasjen** [comment]
I retried this as a fresh deploy and got the same error. FYI. I assume this is just the mock data failing, but let me know.

**Comment by atlasjen** [comment]
Very close!
redeployed to a new scratch org w/o issue.
1) In "new" i uploaded a file and chose SAVE for the CEU and got the following error:
image

2) where do we specify which columns to show in the CEU related object list?
I'd like "Status" to be one of the columns
image

**Comment by atlasjen** [comment]
one more bit of info. I could add files successfully on EDIT just not on NEW.

**Comment by deb761** [comment]
Should be fixed.

**Comment by atlasjen** [comment]
Yep uploading files works well now. Only changes:

Program Title should be required
Program Hours is not required
File upload is required
Status should default to Pending

With these changes, we are good to go.

**Comment by deb761** [comment]
Made last changes.

**Pull request merged**
