### PR TITLE
317 need to add logs for puppy raisers

### LINKED ISSUE #317: Need to add logs for puppy raisers
Our puppy raisers complete logs in form assembly as well as via other methods, so realizing we need to add the concept of logs for puppy raisers. They don't really fit the format of the client/TF logs and I am thinking rather than map all of the data we will want to record a few things in the log entry that can be readily viewed and then save as a PDF.

Here is the form: https://www.tfaforms.com/4967997

I am thinking what we'd want to see for each log quickly in the LWC view
TF name, Dog Name, Date, Do you want support from Atlas, Anything else.
All others could be in the PDF for them to look up.
Confirmed the puppy raising related folks are good w/ these fields.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes

Created Puppy Raiser Log object
Created form for new/edit Puppy Raiser Log
Created Related Puppy Logs component
Created All Related Puppy Logs component

# Issues Closed
#317

### CODE REVIEW

**Review by atlasjen — CHANGES_REQUESTED** [review]
1. We aren't able to submit .docX files in this upload (but can in our normal file upload) 
 
image
2. When submitting from a given contact, can we pre-populate the Puppy Raiser to be that contact?
3. Since the uploaded file is required, can that be marked a required? Actually, we should note that "date", "dog","raiser", and the file are all required. 
4. Date should be required and default to NOW
5. I would assume Puppy Raiser Logs is its own object type i should be able to add to the Quick access menu on top? I'm not seeing it
6. We need to add the related puppy raiser log component to the relevant dog as well

**Comment by deb761** [comment]
Would you want all the normal file types?  I thought you only wanted pdf for this.

**Comment by atlasjen** [comment]
@deb761 
This gave me an error when trying to build the scratch org
Running command: sfdx force:source:push -u 
                    test-976a7nhp6az9@example.com
[09/23/22 18:11:07] *** Pushing with SOAP API v54.0 ***        
[09/23/22 18:12:11] 
                    === Component Failures [28]

                     Type  Name
                    Problem
                     ─────
                    ───────────────────────────────────────────                    ───────────
                    ───────────────────────────────────────────                    ───────────────────────────────────────────                    ───────────────────────────────────────────                    ───────────────────────────────────────────                    ───────────────────────────────────        
                     Error PuppyLogController
                    Variable does not exist: log (37:33)       
                     Error PuppyLogController
                    Variable does not exist: log.Dog__r (36:32)                     Error PuppyLogController
                    Invalid type: Schema.PuppyLog__c (54:29)   
                     Error PuppyLogController
                    Variable does not exist: log (42:77)       
                     Error PuppyLogController
                    Variable does not exist: log (40:35)       
[09/23/22 18:12:12]  Error PuppyLogController
                    Variable does not exist: log (39:32)       
                     Error PuppyLogController
                    Variable does not exist: log.Raiser__r     
                    (38:35)
                     Error PuppyLogController
                    Variable does not exist: log (35:30)       
                     Error PuppyLogController
                    Variable does not exist: log (34:32)       
                     Error PuppyLogController
                    Variable does not exist: log (33:33)       
                     Error PuppyLogController
                    Invalid type: PuppyLog__c (31:18)
                     Error PuppyLogController
                    Invalid type: PuppyLog__c (16:13)
                     Error PupLogFormCmp
                    org.auraframework.throwable.AuraRuntimeExce                    ption: Unable to retrieve metadata for     
                    descriptor:
                    markup://c:__LightningMessageChannel__puppy                    LogForm__c
                     Error PuppyLog__c
                    Error parsing file: The content of elements                    must consist of well-formed character data 
                    or markup. (163:6)
                     Error PuppyLog__c
                    In field: fullName - no CustomObject named 
                    PuppyLog__c found
                     Error ContactRecordPage
                    We couldn't retrieve the design time       
                    component information for component        
                    c:relatedLogsCmp.
                     Error DogRecordPage
                    We couldn't retrieve the design time       
                    component information for component        
                    c:relatedFilesCmp.
                     Error Team
                    We couldn't retrieve the design time       
                    component information for component        
                    c:relatedPatsCmp.
                     Error PuppyLog__c-Puppy Log Layout        
                    Parent entity failed to deploy
                     Error allPuppyLogsCmp
                    LWC1058: Invalid HTML syntax:
                    invalid-first-character-of-tag-name. For   
                    more information, please visit
                    https://html.spec.whatwg.org/multipage/pars                    ing.html#parse-error-invalid-first-characte                    r-of-tag-name (4:2)
                     Error puppyLogFormCmp
                    LWC1503: Parsing error: Unexpected token   
                    (17:0) (17:0)
                     Error relatedObjectCmp
                    LWC1503: Parsing error: Unexpected token   
                    (16:0) (16:0)
                     Error relatedPuppyLogCmp
                    LWC1503: Parsing error: Unexpected token   
                    (63:0) (63:0)
                     Error relatedPuppyLogsCmp
                    LWC1503: Parsing error: Unexpected token   
                    (4:0) (4:0)
                     Error puppyLogForm
                    Error parsing file: The content of elements                    must consist of well-formed character data
                    or markup. (10:2)
                     Error AtlasSuperUser
                    In field: object - no CustomObject named
                    PuppyLog__c found
                     Error Admin
                    In field: field - no CustomObject named
                    PuppyLog__c found
                     Error
                    unfiled$public/Puppy_Logs_with_Puppy_Raiser                    _Report_2te In field: PuppyLog__c - no
                    CustomObject named PuppyLog__c found

[09/23/22 18:12:13] Return code: 1
                    stderr: ERROR running force:source:push:
                    Push failed.

                    Exception in task deploy_unmanaged.dx_push

Error: Return code: 1
stderr: ERROR running force:source:push:  Push failed.

**Comment by deb761** [comment]
Fixed.

**Comment by atlasjen** [comment]
It deployed just fine.
Here are open items:
- date should default to NOW if not set and be required
- please mark the required fields so we know what they are (date, puppy raiser, dog, file)
I love that the log only shows if the person has position=puppy raiser! i would say we would want them to show regardless of status on puppy raiser.. it appears they may only show if active. is that correct?
-nice to have- if creating log under a contact, please auto populate the raiser as the person
-not seeing related logs under the dog

**Comment by deb761** [comment]
Puppy Raiser logs are shown if Puppy Raiser Status != None.

**Comment by atlasjen** [comment]
That works for me!

**Comment by deb761** [comment]
Fixed all issues.

**Pull request merged**
