### PR TITLE
Feature/547 automate a quarterly reminder to active tfs to submit ceus

### LINKED ISSUE #547: Automate a quarterly reminder to Active TFs to submit CEUs
Since we are automating emails to clients and TFs for logs, let's get this one too:

For all Facilitators with Active Status, we want to send a quarterly reminder to submit CEUs.
We can just do this the 1st day of each quarter.

Email would be

---

Subject: Please remember to submit your Atlas Team Facilitator CEUs

Dear `<preferred name>`

This is a quarterly reminder to log your continuing education units. While you can submit them anytime before you renew your certification, it is often easier to do things like this during the year so you can remember what you read, watched, participated in or listened to.

If you are looking for ideas of what to do for CEUs, look at the Facilitator Group in Canvas at the `<a href="https://atlasdogacademy.instructure.com/groups/114/pages/atlas-ceu-options">CEU resource page</a>`. Remember it is as simple as 1 hr of your time spent learning something related to the training you do with our clients = 1 CEU.

ADI requires that all Team Facilitators complete 10 CEU's during each the year, so thank you for making sure to meet this important requirement.

To submit CEUs, simply go to : 
**NOTE for Debbie: replace {stuff } with salesforce fields**
`<a href="https://atlasdog.tfaforms.net/4907434?tfa_2={firstname}&tfa_4={lastname}&tfa_88={email}"> https://atlasdog.tfaforms.net/4907434 </a>.`

If you have more than one CEU to add, just click the "Add CEU" link at the bottom of the form and you can add as many as you want in one submission.

Thank you for being a part of Atlas.

Atlas Assistance Dogs
info@atlasdog.org

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes

1. Added method to ContactService to remind Facilitators
2. Added Schedulable class `RemindFacilitatorsToGetCeus`
3. Added custom metadata type to set email template names.
4. Note: to schedule on the first day of every 3rd month, use this CRON expression: `0 0 0 1 1/3 ? *`

# Issues Closed
#547

### CODE REVIEW

**Comment by atlasjen** [comment]
how should i test this?

**Comment by deb761** [comment]
1. Make sure you have a facilitator set up with an email address you have access to.
2. Got to Settings > Apex Classes > Schedule Apex.
3. Search for `RemindFacilitatorsToGetCeus`
4. Schedule the job to run at least a few minutes in the future.
5. Check the email after it runs.

**Comment by atlasjen** [comment]
OK. setup a facilitator who is active.
scheduled it to run .
it finally did, but w error.
image

I activated it and then cued another job to try to run.

**Comment by atlasjen** [comment]
this is still sitting cued..
image
so i expect it isn't going to run since it was supposed to start every sat at 9pm...

**Comment by atlasjen** [comment]
One comment, i had to go change the filters for visibility of CEUs in the unicorn org. (I think it is fine in prod)
I added the facilitator line
image

I updated the scheduled job you had to see if i can get some emails out :)

**Comment by atlasjen** [comment]
works great. can you go ahead and change the email to be

"each year"
vs
"during each quarter of the year"

then it is ready to go.

**Review by atlasjen — APPROVED** [review]
see comment on email template change. ready after that.

**Comment by deb761** [comment]
Updated template:
image

**Review by atlasjen — APPROVED** [review]
perfect

**Pull request merged**
