### PR TITLE
Change text field lengths

### LINKED ISSUE #283: field length for some of the specify/other fields is short
I was trying to test importing leads from form assembly and realized we have pretty short character limits on some of the specify/other fields.
I'm really hoping we can still change these..... not sure what our datamodel change limitations are at this point. Sorry i just caught this.

**These max at 20 characters:**
**Lead**
Lead. atlas1__pronounOther__c  is text(20)
Lead.atlas1__LeadSourceOther__c  is text(20)

interestingly the field it maps to in contact is 120
**Contact**
Contact.atlas1__LeadSourceOther__c is text(120)
but pronoun is still 20
Contact.atlas1__pronounOther__c  is text(20)

I also see that the Specified things from demographics may be a bit short- particularly the accommodation one.
image

It seems salesforce tends to use Text(128) as its default length for single text fields like title, etc. Let's do that on all of these to be consistent.

It would be wise to go through our custom objects and see where we have "other". I think i caught the remaining ones below.

**CEU**
image

**Dog**
I like that microchip is unique case insensitive, but 30 seems short
let's just make everything 128 to be consistent, same w/ the dog's name
image

**Team**
Name maxes at 80. we should likely be consistent and make it 128, that said i don't care that much on that one.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes
Change field length for Specified... fields to 128 characters.

# Issues Closed
Fixes #283

### CODE REVIEW

**Review by atlasjen — CHANGES_REQUESTED** [review]
All look good other than the microchip one which is still 30.
Make that change and we are set.
thanks!

**Comment by deb761** [comment]
I thought you wanted that one to be limited.

**Comment by atlasjen** [comment]
i wanted it to still be restricted to be unique but to have it be longer.

**Comment by deb761** [comment]
So, what length do you want?  You implied 128 characters in the issue.  40 characters? 60?

**Comment by atlasjen** [comment]
60 works
________________________________

**Review by atlasjen — APPROVED** [review]

**Pull request merged**
