### PR TITLE
308 staff updates

### LINKED ISSUE #308: Staff updates
Contact.StaffStatus picklist is needed
We then also need to update the logic for the quick view that displays status info

Employee
Contractor
Inactive
None

Let's also add "Last Contractor W9" as a field and then add "Contractor W9" as a possible file under staff

And let's change the display in page layout to be "Staff/Contractor Specific Details"

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes

Added W9 File type under Staff category.
Added StaffW9Received field
Added field to Contact layout under Staff/Contractor Specific Details
Updated python script to create File service tests because many fields weren't tested
Added tests for list version: updateDates

# Issues Closed
#308

### CODE REVIEW

**Review by atlasjen — CHANGES_REQUESTED** [review]
Label for staff in page layout is good :)

I uploaded a w4 and the date didn't update.
Similarly, i uploaded a w9 and the data didn't update.
image

I did multiple refreshes.

Status is also not showing at all.
image

**Comment by deb761** [comment]
Check out PR for #315.  The generated code fixes under that should fix this.

**Comment by atlasjen** [comment]
I commited PR #315 and then grabbed these changes in this PR and pushed to the same org. I still don't see "Status" displayed for staff 
image

**Comment by deb761** [comment]
This one is fixed.  Should be able to merge and Staff Status added to layout.

**Comment by atlasjen** [comment]
checked out a new repo and started fresh. Getting this error
image

**Pull request merged**
