### PR TITLE
Feature/254 demographic data

### LINKED ISSUE #254: We need to add demographic data for contacts
We need to add demographic data for contacts.
We will definitely be wanting to protect access to it.
I am thinking we update the Contact Form and people can add the data there if they choose to.
**@debbie: I am not seeing any built in demographic fields so wanted to check w/ you on this and see if you see any.**

I am waiting to hear back from the people in the board who are working on this about exactly which categories we will include, but most likely:

Age
Gender
Education
Marital status
Race
Ethnicity
Religion
Language
Veteran Status
Disability Status

We are going to have people complete updated Contact Forms w/ this info and then we can use dataloader to get those in.

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

Added demographic data
Added ClientValidUntil
Added Trigger on Team__c.PatValidUntil

# Changes

# Issues Closed
#254 #249 #259

### CODE REVIEW

**Review by atlasjen — CHANGES_REQUESTED** [review]
* Can we rename to ClientCertificationValidUntil_c  and display label "Client Certification Valid Until"
* Is TrainerCertificationValidUntil derived? I noticed it is read-only in the page layout and i can't change that.
* Can you change the display label on Specified Pronoun to be "Specified Pronoun"  vs "Pronoun (Entered)" that keeps it consistent w the rest
***I added this into my commit but I removed Notes from the related list for Atlas Contact Layout so i could try to add it to the quick access bar on the right, but now i can't find out how to access it at all.**


All else looks good.

**Comment by deb761** [comment]
I changed the field name and restored Notes to the bottom of the Atlas Contact Layout. 
TrainerCertificationValidUntil__c is derived: it is 365 days after TrainerCertAgreementReceived__c.
Set the page layouts for Account to be the Organization and Household layouts.  The Organization layout includes Email.

**Comment by atlasjen** [comment]
* Organization Page Layout does include email, but it's not assigned "Account Layout" is the one assigned and also what impact the New form. It seems to me we should update the Account Layout since some accounts are household (most) and some are organization (few).. using the main account layout seems ok to me.

* Let's put this formula for FacilitatorCertificationValidUntil
FacilitatorCertAgreementReceived__c + 365
and then we can make that field locked in the page layout.

*Confirm that Notes are back in related, Confirm Client cert valid rename.

**Comment by deb761** [comment]
When you create a Contact, a household account is automatically created.  When you create an Account for a Vet, it is an Organizational account.  And it doesn't look like you can create an account that isn't an Organization or a Household.

**Comment by atlasjen** [comment]
merging in. Will add a separate issue for the Team Facilitator Valid until date.

**Pull request merged**
