### PR TITLE
492 sharing rules

### LINKED ISSUE #492: addl changes for AtlasVolunteer role
let's also hide any contact info fields for anyone who is not a volunteer
is this doable? i know salesforce uses these to dedupe, so not sure if that is an issue.
this would apply to contact and account.

i am thinking we hide these on contact:
email, personal email, phone, other phone, alternate email , birthdate, pronoun, specified pronoun, mailing address, other address
and hide these on account:
phone, billing address, shipping address

### PR DESCRIPTION
**Pull request by deb761**
# Critical Changes

# Changes
Added relationship trigger that adds ShareWith to related contacts that match main contact.  Added relationship object to Volunteer permission set.

Known bug where if position removed the ShareWith on related contact isn't removed.

# Issues Closed
#492

### CODE REVIEW

**Comment by atlasjen** [comment]
relationships that are created by the test user w/ volunteer permissions are visible. no other relationships are (and neither are contacts or accounts)

**Comment by deb761** [comment]
I missed adding the sharing rules in post deploy.

**Comment by deb761** [comment]
I have something that's working in a scratch org, but there's a bit of setup involved:

1. Create Custom Setting "Atlas Settings"
2. Update Sharing Settings for Contact and Lead
3. Add a Sharing rule for group Volunteer that uses ShareWithVolunteer
4. Add User User to Group "All"
5. Create Volunteer User with Atlas Minimum Profile
6. Add Volunteer to Volunteer Group
7. Assign Atlas Base and Atlas Volunteer permission sets to your volunteer

I am setting up the deb sandbox for testing this.

**Comment by atlasjen** [comment]
more detailed setup notes:
1.Create Custom Setting "Atlas Settings"
image

2. Update Sharing Settings for Contact and Lead
image
3.Add a Sharing rule for group Volunteer that uses ShareWithVolunteer
image

4.Add User User to Group "All"
image

5.Create Volunteer User with Atlas Minimum Profile

6.Add Volunteer to Volunteer Group
image

7.Assign Atlas Base and Atlas Volunteer permission sets to your volunteer
image

then open developer console from salesforce
To set the fields, pull up a Developer Console, and Debug > Open Execute Anonymous and paste in the following.  Then press execute.  
`Postinstall.setSharingFields();`

**Pull request merged**
